spring.application.name=discografia

# Configuracion conexion a MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://eva2_spring:1234@cluster-spring.7bidxwu.mongodb.net/?retryWrites=true&w=majority&appName=cluster-spring
spring.data.mongodb.database=discografica-db